--11.Calculate the total revenue generated by each pizza type.
select pt.name_ as pizza_name,
sum(od.quantity*p.price) as total_revenue from order_details od
join pizzas p
on od.pizza_id=p.pizza_id
join pizza_type pt 
on p.pizza_type_id=pt.pizza_type_id
group by pt.name_
order by total_revenue desc;

--12.Calculate the total revenue generated from pizza sales.
SELECT SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id;

--13.Find the total revenue generated from each pizza category.
SELECT pt.category,SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p 
ON od.pizza_id = p.pizza_id
JOIN pizza_type pt 
ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY total_revenue DESC;

--14.Find the number of orders placed in each hour of the day.
SELECT 
HOUR(time_) AS order_hour,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_hour
ORDER BY total_orders DESC;

--15.Calculate the average price of pizzas for each size.
SELECT size_,AVG(price) AS avg_price
FROM pizzas
GROUP BY size_
ORDER BY size_;

--16.Find the category with the highest total quantity sold.
SELECT pt.category,SUM(od.quantity) AS total_quantity
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_type pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY total_quantity DESC
LIMIT 1;

--17.Find pizzas that were never ordered.
SELECT p.pizza_id
FROM pizzas p
LEFT JOIN order_details od 
ON p.pizza_id = od.pizza_id
WHERE od.pizza_id IS NULL;

--18.Find all orders where total quantity is greater than 3.
SELECT p.size_,SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p 
ON od.pizza_id = p.pizza_id
GROUP BY p.size_
ORDER BY total_revenue DESC
LIMIT 1;

--19.Find which pizza size generates the highest revenue.
SELECT p.size_,SUM(od.quantity * p.price) AS total_revenue
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
GROUP BY p.size_
ORDER BY total_revenue DESC
LIMIT 1;

--20.Find orders where quantity is greater than average quantity.
SELECT * FROM order_details
WHERE quantity > (
SELECT AVG(quantity) FROM order_details
);
